apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: bridge-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: bridge-topic-1
      operation: Write
    - resource:
        type: topic
        name: bridge-topic-1
      operation: Describe
    - resource:
        type: topic
        name: bridge-topic-1
      operation: Read
    - resource:
        type: topic
        name: bridge-topic-1
      operation: Create
    - resource:
        type: group
        name: bridge-group
      operation: Read