apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kafka-connector-sink
objects:
- apiVersion: kafka.strimzi.io/v1alpha1
  kind: KafkaConnector
  metadata:
    name: jdbc-sink-connector
    labels:
      strimzi.io/cluster: ${KAFKA_CONNECT_NAME}
  spec:
    class: 'io.confluent.connect.jdbc.JdbcSinkConnector'
    tasksMax: 1
    config:
      topics: 'customers'
      connection.url: 'jdbc:postgresql://${POSTGRESQL_HOST}:5432/inventory?user=postgresuser&password=postgrespw'
      transforms: 'unwrap'
      transforms.unwrap.type: 'io.debezium.transforms.ExtractNewRecordState'
      transforms.unwrap.drop.tombstones: 'false'
      auto.create: 'true'
      insert.mode: 'upsert'
      delete.enabled: 'true'
      pk.fields: 'id'
      pk.mode: 'record_key'
parameters:
- name: KAFKA_CONNECT_NAME
  value: kafka-connect
- name: POSTGRESQL_HOST
